# Generated by Django 5.0.6 on 2025-10-13 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_home', models.FloatField()),
                ('prob_draw', models.FloatField()),
                ('prob_away', models.FloatField()),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10)),
                ('explain', models.JSONField(default=list)),
                ('recalculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='core.match')),
            ],
            options={
                'ordering': ['-recalculated_at'],
            },
        ),
    ]
